In [1]:
import numpy as np

arr = np.arange(1,17).reshape(4,4)
print(arr)
print('second row: ',arr[1, :])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
second row:  [5 6 7 8]


In [2]:
print('third column:',arr[:,3])

third column: [ 4  8 12 16]


In [3]:
print('top right 2x2 submatrix:',arr[0:2,2:4])

top right 2x2 submatrix: [[3 4]
 [7 8]]


In [4]:
arr1 = np.random.randint(1,10,(3,3))
arr2 = np.random.randint(1,10,(3,3))

print('element-wise addition',np.add(arr1,arr2))
print('element-wise subtraction',np.subtract(arr1,arr2))
print('element-wise multiply',np.multiply(arr1,arr2))
print('matrix multiplication',(arr1@arr2))


element-wise addition [[15  8  5]
 [ 5  7  8]
 [14  7 11]]
element-wise subtraction [[ 3 -4  1]
 [ 1  5 -6]
 [-2  1 -3]]
element-wise multiply [[54 12  6]
 [ 6  6  7]
 [48 12 28]]
matrix multiplication [[82 65 53]
 [38 27 55]
 [76 52 68]]


In [5]:
arr3 = np.random.randint(50,100,size= 10)
print(arr3)
print("max num:",np.max(arr3),"index of max:",np.argmax(arr3))

[79 51 93 97 73 65 99 75 88 50]
max num: 99 index of max: 6


In [6]:
print("max num:",np.min(arr3),"index of max:",np.argmin(arr3))


max num: 50 index of max: 9


In [7]:
print(arr3[arr3%2==0].mean())

69.0


In [8]:
arr4 = np.random.randint(1,50,(6,6))
print(arr4)

avg_arr4 = arr4.mean()
print('average:',avg_arr4)

[[36 48  9 37 37 43]
 [ 2 11  7 43 17 34]
 [19 10 43 21 33 46]
 [43 23 38 14 35  3]
 [44 46 48 14 25 43]
 [47 16 34 31 10 39]]
average: 29.13888888888889


In [9]:
arr4[arr4 > avg_arr4] = 0
print(arr4)

# or do this to save original array
arr4_modified = arr4.copy()
arr4_modified[arr4_modified > avg_arr4] = 0
print(arr4_modified)


[[ 0  0  9  0  0  0]
 [ 2 11  7  0 17  0]
 [19 10  0 21  0  0]
 [ 0 23  0 14  0  3]
 [ 0  0  0 14 25  0]
 [ 0 16  0  0 10  0]]
[[ 0  0  9  0  0  0]
 [ 2 11  7  0 17  0]
 [19 10  0 21  0  0]
 [ 0 23  0 14  0  3]
 [ 0  0  0 14 25  0]
 [ 0 16  0  0 10  0]]


In [10]:
arr5 = np.random.randint(1,11,(2,3,4))
print(arr5)

print("sum at axis 0: ",np.sum(arr5,axis=0))
print("sum at axis 1: ",np.sum(arr5,axis=1))
print("max: ",np.max(arr5))




[[[10  7  6  8]
  [ 3  3  5  8]
  [ 3  3  6 10]]

 [[ 1  2  8  4]
  [ 7  2  5  6]
  [ 7  2  8  5]]]
sum at axis 0:  [[11  9 14 12]
 [10  5 10 14]
 [10  5 14 15]]
sum at axis 1:  [[16 13 17 26]
 [15  6 21 15]]
max:  10


In [11]:
iden_mat = np.identity(5)

iden_mat = np.fill_diagonal(iden_mat,7)
print(iden_mat)

None


In [12]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6]])
print(np.concatenate((a,b),axis=0))


[[1 2]
 [3 4]
 [5 6]]


In [13]:
arr6 = np.arange(1,16)
arr61, arr62, arr63=np.split(arr6,3)
print(arr61)
print(arr62)
print(arr63)

#print(np.vstack(arr61,arr62,arr63))



[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


In [14]:
arr7 = np.random.randint(1,30,(5,5))
arr7[arr7%2==0]=0

In [15]:
import pandas as pd 
import numpy as np

people = {
    'name':  ['Ali','Ahmad','Ayesha','Umer','Saad','Fatima'],
    'Age' : [7,11,5,20,14,19],
    'city' : ['pesh','isb','swat','lahore','karachi','mardan']
}

people_df = pd.DataFrame(people)
print(people_df)

     name  Age     city
0     Ali    7     pesh
1   Ahmad   11      isb
2  Ayesha    5     swat
3    Umer   20   lahore
4    Saad   14  karachi
5  Fatima   19   mardan


In [16]:
array = np.random.randint(1,11,(4,3))

array_df = pd.DataFrame(array)
print(array_df)
array_df.rename(columns={0:'first',1:'second',2:'third'},inplace=True)
print(array_df)


   0  1  2
0  2  1  4
1  6  1  7
2  5  4  9
3  3  6  1
   first  second  third
0      2       1      4
1      6       1      7
2      5       4      9
3      3       6      1


In [17]:
data_csv = pd.read_csv("https://raw.githubusercontent.com/plotly/datasets/master/gapminderDataFiveYear.csv")

print(data_csv.head())

       country  year         pop continent  lifeExp   gdpPercap
0  Afghanistan  1952   8425333.0      Asia   28.801  779.445314
1  Afghanistan  1957   9240934.0      Asia   30.332  820.853030
2  Afghanistan  1962  10267083.0      Asia   31.997  853.100710
3  Afghanistan  1967  11537966.0      Asia   34.020  836.197138
4  Afghanistan  1972  13079460.0      Asia   36.088  739.981106


In [18]:
data_clipboard = pd.read_clipboard()

print(data_clipboard)

Empty DataFrame
Columns: [data_csv.drop('continent',, axis=1,, inplace=True)]
Index: []


In [19]:
print("shape:",data_csv.shape,"\nnumber of rows:",len(data_csv),"\ncolumns",data_csv.shape[1])

shape: (1704, 6) 
number of rows: 1704 
columns 6


In [20]:
print(data_csv.loc[data_csv['year']>2000,'country'])

10      Afghanistan
11      Afghanistan
22          Albania
23          Albania
34          Algeria
           ...     
1679    Yemen, Rep.
1690         Zambia
1691         Zambia
1702       Zimbabwe
1703       Zimbabwe
Name: country, Length: 284, dtype: object


In [21]:
# or

print(data_csv.query("year>2000")["country"])

10      Afghanistan
11      Afghanistan
22          Albania
23          Albania
34          Algeria
           ...     
1679    Yemen, Rep.
1690         Zambia
1691         Zambia
1702       Zimbabwe
1703       Zimbabwe
Name: country, Length: 284, dtype: object


In [22]:
print(data_csv.iloc[0:5])

print("with loc")
print(data_csv.loc[0:4])


       country  year         pop continent  lifeExp   gdpPercap
0  Afghanistan  1952   8425333.0      Asia   28.801  779.445314
1  Afghanistan  1957   9240934.0      Asia   30.332  820.853030
2  Afghanistan  1962  10267083.0      Asia   31.997  853.100710
3  Afghanistan  1967  11537966.0      Asia   34.020  836.197138
4  Afghanistan  1972  13079460.0      Asia   36.088  739.981106
with loc
       country  year         pop continent  lifeExp   gdpPercap
0  Afghanistan  1952   8425333.0      Asia   28.801  779.445314
1  Afghanistan  1957   9240934.0      Asia   30.332  820.853030
2  Afghanistan  1962  10267083.0      Asia   31.997  853.100710
3  Afghanistan  1967  11537966.0      Asia   34.020  836.197138
4  Afghanistan  1972  13079460.0      Asia   36.088  739.981106


In [23]:
print(data_csv[['gdpPercap','year']].tail())

       gdpPercap  year
1699  706.157306  1987
1700  693.420786  1992
1701  792.449960  1997
1702  672.038623  2002
1703  469.709298  2007


In [24]:
print(data_csv.tail(3))

       country  year         pop continent  lifeExp   gdpPercap
1701  Zimbabwe  1997  11404948.0    Africa   46.809  792.449960
1702  Zimbabwe  2002  11926563.0    Africa   39.989  672.038623
1703  Zimbabwe  2007  12311143.0    Africa   43.487  469.709298


In [25]:
print(data_csv.query('continent=="Asia"'))

          country  year         pop continent  lifeExp    gdpPercap
0     Afghanistan  1952   8425333.0      Asia   28.801   779.445314
1     Afghanistan  1957   9240934.0      Asia   30.332   820.853030
2     Afghanistan  1962  10267083.0      Asia   31.997   853.100710
3     Afghanistan  1967  11537966.0      Asia   34.020   836.197138
4     Afghanistan  1972  13079460.0      Asia   36.088   739.981106
...           ...   ...         ...       ...      ...          ...
1675  Yemen, Rep.  1987  11219340.0      Asia   52.922  1971.741538
1676  Yemen, Rep.  1992  13367997.0      Asia   55.599  1879.496673
1677  Yemen, Rep.  1997  15826497.0      Asia   58.020  2117.484526
1678  Yemen, Rep.  2002  18701257.0      Asia   60.308  2234.820827
1679  Yemen, Rep.  2007  22211743.0      Asia   62.698  2280.769906

[396 rows x 6 columns]


In [26]:
print(data_csv['country'][data_csv['lifeExp']>70])

18                 Albania
19                 Albania
20                 Albania
21                 Albania
22                 Albania
               ...        
1654               Vietnam
1655               Vietnam
1665    West Bank and Gaza
1666    West Bank and Gaza
1667    West Bank and Gaza
Name: country, Length: 493, dtype: object


In [27]:
#print(data_csv[(data_csv['lifeExp'] < 75) & (data_csv['gdpPercap'] > 20000)])
print(data_csv.query('lifeExp <75 and gdpPercap>20000'))

            country  year          pop continent  lifeExp     gdpPercap
78          Austria  1982    7574613.0    Europe   73.180   21597.08362
79          Austria  1987    7578903.0    Europe   74.940   23687.82607
93          Bahrain  1997     598561.0      Asia   73.925   20292.01679
94          Bahrain  2002     656397.0      Asia   74.795   23403.55927
114         Belgium  1982    9856303.0    Europe   73.930   20979.84589
245          Canada  1977   23796400.0  Americas   74.210   22090.88306
413         Denmark  1977    5088419.0    Europe   74.690   20422.90150
414         Denmark  1982    5117810.0    Europe   74.630   21688.04048
415         Denmark  1987    5127024.0    Europe   74.800   25116.17581
523         Finland  1987    4931729.0    Europe   74.830   21141.01223
534          France  1982   54433565.0    Europe   74.890   20293.89746
545           Gabon  1977     706367.0    Africa   52.790   21745.57328
569         Germany  1977   78160773.0    Europe   72.500   2051

In [28]:
print(data_csv[data_csv['country'].str.contains('p',case=False)])

                       country  year         pop continent  lifeExp  \
252   Central African Republic  1952   1291695.0    Africa   35.463   
253   Central African Republic  1957   1392284.0    Africa   37.464   
254   Central African Republic  1962   1523478.0    Africa   39.475   
255   Central African Republic  1967   1733638.0    Africa   41.478   
256   Central African Republic  1972   1927260.0    Africa   43.457   
...                        ...   ...         ...       ...      ...   
1675               Yemen, Rep.  1987  11219340.0      Asia   52.922   
1676               Yemen, Rep.  1992  13367997.0      Asia   55.599   
1677               Yemen, Rep.  1997  15826497.0      Asia   58.020   
1678               Yemen, Rep.  2002  18701257.0      Asia   60.308   
1679               Yemen, Rep.  2007  22211743.0      Asia   62.698   

        gdpPercap  
252   1071.310713  
253   1190.844328  
254   1193.068753  
255   1136.056615  
256   1070.013275  
...           ...  
1675  1

In [29]:
print(data_csv.query('pop >1e8'))

            country  year          pop continent  lifeExp     gdpPercap
103      Bangladesh  1987  103764241.0      Asia   52.819    751.979403
104      Bangladesh  1992  113704579.0      Asia   56.018    837.810164
105      Bangladesh  1997  123315288.0      Asia   59.412    972.770035
106      Bangladesh  2002  135656790.0      Asia   62.013   1136.390430
107      Bangladesh  2007  150448339.0      Asia   64.062   1391.253792
...             ...   ...          ...       ...      ...           ...
1615  United States  1987  242803533.0  Americas   75.020  29884.350410
1616  United States  1992  256894189.0  Americas   76.090  32003.932240
1617  United States  1997  272911760.0  Americas   76.810  35767.433030
1618  United States  2002  287675526.0  Americas   77.310  39097.099550
1619  United States  2007  301139947.0  Americas   78.242  42951.653090

[77 rows x 6 columns]


In [30]:
data_csv['GDP_Total'] =data_csv['pop']*data_csv['gdpPercap']
print(data_csv.head())

       country  year         pop continent  lifeExp   gdpPercap     GDP_Total
0  Afghanistan  1952   8425333.0      Asia   28.801  779.445314  6.567086e+09
1  Afghanistan  1957   9240934.0      Asia   30.332  820.853030  7.585449e+09
2  Afghanistan  1962  10267083.0      Asia   31.997  853.100710  8.758856e+09
3  Afghanistan  1967  11537966.0      Asia   34.020  836.197138  9.648014e+09
4  Afghanistan  1972  13079460.0      Asia   36.088  739.981106  9.678553e+09


In [31]:
data_csv.rename(columns={'lifeExp':'Life-expectency'},inplace=True)
print(data_csv.columns)

Index(['country', 'year', 'pop', 'continent', 'Life-expectency', 'gdpPercap',
       'GDP_Total'],
      dtype='object')


In [32]:
data_csv.columns = data_csv.columns.str.lower()
print(data_csv.columns)

Index(['country', 'year', 'pop', 'continent', 'life-expectency', 'gdppercap',
       'gdp_total'],
      dtype='object')


In [33]:
print(data_csv[data_csv.isna().any(axis=1)])

print(data_csv.isna().sum())



Empty DataFrame
Columns: [country, year, pop, continent, life-expectency, gdppercap, gdp_total]
Index: []
country            0
year               0
pop                0
continent          0
life-expectency    0
gdppercap          0
gdp_total          0
dtype: int64


In [34]:
data_csv.fillna(0, inplace=True) 
print(data_csv)

          country  year         pop continent  life-expectency   gdppercap  \
0     Afghanistan  1952   8425333.0      Asia           28.801  779.445314   
1     Afghanistan  1957   9240934.0      Asia           30.332  820.853030   
2     Afghanistan  1962  10267083.0      Asia           31.997  853.100710   
3     Afghanistan  1967  11537966.0      Asia           34.020  836.197138   
4     Afghanistan  1972  13079460.0      Asia           36.088  739.981106   
...           ...   ...         ...       ...              ...         ...   
1699     Zimbabwe  1987   9216418.0    Africa           62.351  706.157306   
1700     Zimbabwe  1992  10704340.0    Africa           60.377  693.420786   
1701     Zimbabwe  1997  11404948.0    Africa           46.809  792.449960   
1702     Zimbabwe  2002  11926563.0    Africa           39.989  672.038623   
1703     Zimbabwe  2007  12311143.0    Africa           43.487  469.709298   

         gdp_total  
0     6.567086e+09  
1     7.585449e+09  


In [35]:
cols= ['country','pop','year','life-expectency','gdp_total','gdppercap','continent']
data_csv = data_csv[cols]
print(data_csv)

          country         pop  year  life-expectency     gdp_total  \
0     Afghanistan   8425333.0  1952           28.801  6.567086e+09   
1     Afghanistan   9240934.0  1957           30.332  7.585449e+09   
2     Afghanistan  10267083.0  1962           31.997  8.758856e+09   
3     Afghanistan  11537966.0  1967           34.020  9.648014e+09   
4     Afghanistan  13079460.0  1972           36.088  9.678553e+09   
...           ...         ...   ...              ...           ...   
1699     Zimbabwe   9216418.0  1987           62.351  6.508241e+09   
1700     Zimbabwe  10704340.0  1992           60.377  7.422612e+09   
1701     Zimbabwe  11404948.0  1997           46.809  9.037851e+09   
1702     Zimbabwe  11926563.0  2002           39.989  8.015111e+09   
1703     Zimbabwe  12311143.0  2007           43.487  5.782658e+09   

       gdppercap continent  
0     779.445314      Asia  
1     820.853030      Asia  
2     853.100710      Asia  
3     836.197138      Asia  
4     739.9811

In [36]:
print(data_csv.groupby('continent')['pop'].agg(['min', 'max']))



                 min           max
continent                         
Africa       60011.0  1.350312e+08
Americas    662850.0  3.011399e+08
Asia        120447.0  1.318683e+09
Europe      147962.0  8.240100e+07
Oceania    1994794.0  2.043418e+07


In [37]:
print(data_csv['gdppercap'].corr(data_csv['life-expectency']))


0.5837062198659948


In [38]:
print(data_csv.groupby('continent')['gdppercap'].mean())


continent
Africa       2193.754578
Americas     7136.110356
Asia         7902.150428
Europe      14469.475533
Oceania     18621.609223
Name: gdppercap, dtype: float64


In [39]:
students = pd.DataFrame({
    'ID': [1,2,3],
    'Name': ['Ali','Sara','Zain']
})

marks = pd.DataFrame({
    'ID': [1,2,3],
    'Score': [85, 90, 78]
})
merged_df = students.merge(marks, on='ID')
print(merged_df)


   ID  Name  Score
0   1   Ali     85
1   2  Sara     90
2   3  Zain     78


In [40]:
concat_vert = pd.concat([students, students], ignore_index=True)
print(concat_vert)


   ID  Name
0   1   Ali
1   2  Sara
2   3  Zain
3   1   Ali
4   2  Sara
5   3  Zain


In [41]:
concat_horiz = pd.concat([students, marks], axis=1)
print(concat_horiz)


   ID  Name  ID  Score
0   1   Ali   1     85
1   2  Sara   2     90
2   3  Zain   3     78


In [42]:
left_join = students.merge(marks, on='ID', how='left')
print(left_join)


   ID  Name  Score
0   1   Ali     85
1   2  Sara     90
2   3  Zain     78


In [43]:
extra = pd.DataFrame({'ID':[1,2,3],'Age':[20,21,22]})
merged_three = students.merge(marks, on='ID').merge(extra, on='ID')
print(merged_three)


   ID  Name  Score  Age
0   1   Ali     85   20
1   2  Sara     90   21
2   3  Zain     78   22


In [44]:
data_csv.drop('continent', axis=1, inplace=True)
print(data_csv)

          country         pop  year  life-expectency     gdp_total   gdppercap
0     Afghanistan   8425333.0  1952           28.801  6.567086e+09  779.445314
1     Afghanistan   9240934.0  1957           30.332  7.585449e+09  820.853030
2     Afghanistan  10267083.0  1962           31.997  8.758856e+09  853.100710
3     Afghanistan  11537966.0  1967           34.020  9.648014e+09  836.197138
4     Afghanistan  13079460.0  1972           36.088  9.678553e+09  739.981106
...           ...         ...   ...              ...           ...         ...
1699     Zimbabwe   9216418.0  1987           62.351  6.508241e+09  706.157306
1700     Zimbabwe  10704340.0  1992           60.377  7.422612e+09  693.420786
1701     Zimbabwe  11404948.0  1997           46.809  9.037851e+09  792.449960
1702     Zimbabwe  11926563.0  2002           39.989  8.015111e+09  672.038623
1703     Zimbabwe  12311143.0  2007           43.487  5.782658e+09  469.709298

[1704 rows x 6 columns]
